platform :ios, '7.0'

pod 'RETableViewManager', :git => 'https://github.com/romaonthego/RETableViewManager'
pod 'MJRefresh', :git => 'https://github.com/CoderMJLee/MJRefresh'
pod 'MJExtension', :git => 'https://github.com/CoderMJLee/MJExtension'
pod 'SDWebImage', :git => 'https://github.com/rs/SDWebImage'
